#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Marathi Disfluency Correction (Zero-shot, Prompt-only) with Llama 3.2-3B-Instruct via vLLM.

Usage example:
python disfluency_infer_Marathi_llama32.py \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --disfluent "/path/to/Marathi_test.processed.dis" \
  --out_jsonl runs/Marathi_llama32.jsonl \
  --out_txt runs/Marathi_llama32.txt \
  --tp 1 --dtype bfloat16 --gpu_util 0.6 --max_model_len 2048 \
  --max_tokens 128 --temperature 0.0
"""

import argparse
import json
from pathlib import Path
from typing import List

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams


SYSTEM_INSTRUCTION = (
    "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
    "This sentence may contain disfluencies, including but not limited to repetitions, fillers, "
    "discourse markers, and false starts in Marathi.\n"
    "Your task is to remove these disfluencies while preserving the grammatical structure and meaning.\n"
    "Return only the corrected, well-formed fluent Marathi sentence. Do not add explanations, labels, or quotes."
)

USER_TEMPLATE = """Language: Marathi
Disfluent ASR sentence:
{disfluent}
"""


def read_lines(p: str) -> List[str]:
    with open(p, "r", encoding="utf-8") as f:
        return [line.rstrip("\n\r") for line in f]


def build_chat_prompt(tokenizer, disfluent: str) -> str:
    # Slight guard so triple-backticks inside input don't prematurely stop generation
    disfluent_safe = disfluent.replace("```", "``` ")
    messages = [
        {"role": "system", "content": SYSTEM_INSTRUCTION},
        {"role": "user", "content": USER_TEMPLATE.format(disfluent=disfluent_safe)},
    ]
    # vLLM uses the HF chat template for meta-llama/Llama-3.2-3B-Instruct
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


def main():
    ap = argparse.ArgumentParser(
        description="Zero-shot disfluency correction (Marathi) with Llama 3.2-3B-Instruct via vLLM."
    )
    ap.add_argument(
        "--model",
        default="meta-llama/Llama-3.2-3B-Instruct",
        help="HF model id or local path (chat/instruct model).",
    )
    ap.add_argument(
        "--disfluent",
        required=True,
        help="Text file with one disfluent Marathi sentence per line.",
    )
    ap.add_argument(
        "--out_jsonl",
        default="Marathi_corrected.jsonl",
        help="Output JSONL with {disfluent, corrected}.",
    )
    ap.add_argument(
        "--out_txt",
        default="Marathi_corrected.txt",
        help="Output TXT with one corrected line.",
    )
    ap.add_argument("--tp", type=int, default=1, help="vLLM tensor_parallel_size")
    ap.add_argument(
        "--dtype",
        default="bfloat16",
        choices=["bfloat16", "float16", "float32"],
        help="Computation dtype.",
    )
    ap.add_argument(
        "--gpu_util",
        type=float,
        default=0.55,
        help="vLLM gpu_memory_utilization (0.1–0.95).",
    )
    ap.add_argument(
        "--max_model_len",
        type=int,
        default=2048,
        help="Reduce if GPU memory is tight (e.g., 1024).",
    )
    ap.add_argument("--max_tokens", type=int, default=128)
    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--top_p", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    # Load inputs
    disfluent_lines = read_lines(args.disfluent)
    if not disfluent_lines:
        raise SystemExit("[error] Empty disfluent file.")

    # Tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=False)
    llm = LLM(
        model=args.model,
        tensor_parallel_size=args.tp,
        dtype=args.dtype,
        trust_remote_code=False,
        gpu_memory_utilization=args.gpu_util,
        max_model_len=args.max_model_len,
    )

    # Build prompts for all lines
    prompts = [build_chat_prompt(tokenizer, d) for d in disfluent_lines]

    # Stop on EOS and Llama 3.x end-of-turn if available
    stop_token_ids = []
    if tokenizer.eos_token_id is not None:
        stop_token_ids.append(tokenizer.eos_token_id)
    try:
        eot_id = tokenizer.convert_tokens_to_ids("<|eot_id|>")
        if eot_id is not None and eot_id != tokenizer.unk_token_id:
            stop_token_ids.append(eot_id)
    except Exception:
        pass  # If template/token is missing, EOS alone is fine.

    sampling = SamplingParams(
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        stop_token_ids=stop_token_ids,
        seed=args.seed,
    )

    # Generate
    outputs = llm.generate(prompts, sampling)
    raw_generations = [o.outputs[0].text if (o.outputs and o.outputs[0].text is not None) else "" for o in outputs]

    # Clean model text → fluent sentence
    def clean(text: str) -> str:
        s = (text or "").strip()
        # Remove wrapping quotes if present
        if len(s) >= 2 and (s[0] == s[-1]) and s[0] in ['"', "“", "”", "‘", "’", "'"]:
            s = s[1:-1].strip()
        # Strip any accidental label prefixes
        for prefix in ["Corrected:", "Output:", "Fluent:", "Correction:", "उत्तर:", "आउटपुट:", "सुधारणा:"]:
            if s.lower().startswith(prefix.lower()):
                s = s[len(prefix):].strip()
        return s

    corrected = [clean(g) for g in raw_generations]

    # Write outputs
    out_jsonl = Path(args.out_jsonl)
    out_txt = Path(args.out_txt)
    out_jsonl.parent.mkdir(parents=True, exist_ok=True)
    out_txt.parent.mkdir(parents=True, exist_ok=True)

    with open(out_jsonl, "w", encoding="utf-8") as f:
        for d_in, d_out in zip(disfluent_lines, corrected):
            f.write(json.dumps({"disfluent": d_in, "corrected": d_out}, ensure_ascii=False) + "\n")

    with open(out_txt, "w", encoding="utf-8") as f:
        for d_out in corrected:
            f.write(d_out + "\n")

    print(f"✅ Wrote: {out_jsonl} and {out_txt}")


if __name__ == "__main__":
    main()
