import json

# File paths
dis_file = "/home/paritosh/zero-shot-disfluency-detection/disfluency_signal_llama/data.dis"
label_file = "/home/paritosh/zero-shot-disfluency-detection/disfluency_signal_llama/data.label"
flu_file = "/home/paritosh/zero-shot-disfluency-detection/disfluency_signal_llama/data.flu"
output_file = "/home/paritosh/zero-shot-disfluency-detection/disfluency_signal_llama/alpaca_disfluency_dataset.jsonl"

# Load lines
with open(dis_file, 'r', encoding='utf-8') as f:
    dis_lines = [line.strip().split() for line in f]   # word-level tokens
with open(label_file, 'r', encoding='utf-8') as f:
    label_lines = [list(map(int, line.strip().split())) for line in f]
with open(flu_file, 'r', encoding='utf-8') as f:
    flu_lines = [line.strip() for line in f]

# instruction = (
#     "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
#     "This sentence may contain disfluencies, including but not limited to repetitions, fillers, discourse markers, false starts, and other forms of disfluent speech in Hindi, Bengali and Marathi.\n\n"
#     "Your task is to remove these disfluencies while preserving the grammatical structure and original meaning of the sentence.\n\n"
#     "You are also provided with:\n\n"
#     "- A word-tokenized version of the disfluent sentence, and\n"
#     "- A sequence of predicted labels for each word, where:\n"
#     "    • '1' = the word is disfluent and should be removed\n"
#     "    • '0' = the word is fluent and should be retained\n\n"
#     "Here are some examples of word-label pairs:\n"
#     "    Hindi:  [(\"यह\", 0), (\"किसानों\", 1), (\"के\", 1), (\"किसानों\", 0), (\"के\", 0), (\"पुरुषार्थ\", 0)]\n"
#     "    Bengali: [(\"হ্যাঁ\", 0), (\"আহ\", 1), (\",\", 0), (\"কি\", 0), (\"নিয়ে\", 0), (\"সাদা\", 0), (\"রঙের\", 0)]\n"
#     "    Marathi: [(\"आम्ही\", 0), (\"म्हणजे\", 1), (\"आम्ही\", 0), (\"शेतकरी\", 0), (\"काम\", 0), (\"करतो\", 0)]\n"
#     "After removing words labeled as '1', reconstruct the fluent sentence.\n\n"
#     "Ensure that the final output is a well-formed, fluent sentence that conveys the same intended meaning as the original input, but without any disfluencies."
# )


instruction = (
    "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
    "This sentence may contain disfluencies, including but not limited to repetitions, fillers, discourse markers, false starts, and other forms of disfluent speech in Hindi, Bengali and Marathi.\n\n"
    "Your task is to remove these disfluencies while preserving the grammatical structure and original meaning of the sentence.\n\n"
    "You are also provided with:\n\n"
    "- A word-tokenized version of the disfluent sentence, and\n"
    "- A sequence of predicted labels for each word, where:\n"
    "    • '1' = the word is disfluent and should be removed\n"
    "    • '0' = the word is fluent and should be retained\n\n"
    "Here is an example of word-label pairs:\n"
    "    Hindi: [(\"यह\", 0), (\"किसानों\", 1), (\"के\", 1), (\"किसानों\", 0), (\"के\", 0), (\"पुरुषार्थ\", 0)]\n\n"
    "After removing words labeled as '1', reconstruct the fluent sentence.\n\n"
    "Ensure that the final output is a well-formed, fluent sentence that conveys the same intended meaning as the original input, but without any disfluencies."
)


# Sanity check
assert len(dis_lines) == len(label_lines) == len(flu_lines), "Mismatch in number of lines!"

# Write JSONL
with open(output_file, "w", encoding="utf-8") as out:
    for dis_tokens, labels, flu in zip(dis_lines, label_lines, flu_lines):
        assert len(dis_tokens) == len(labels), f"Word/Label mismatch: {dis_tokens} vs {labels}"
        
        word_labels = list(zip(dis_tokens, labels))
        dis_sent = " ".join(dis_tokens)

        data = {
            "instruction": instruction,
            "input": f"Words + Labels: {word_labels}\nDisfluent Sentence: {dis_sent}",
            "output": flu
        }
        out.write(json.dumps(data, ensure_ascii=False) + "\n")

print("✅ Word-level dataset saved to:", output_file)
