#!/usr/bin/env python3
"""
Generate fluent sentences from disfluent ASR outputs using a trained language model.

Usage:
    python generate_fluent_from_preds.py \
        --generator_model /path/to/final_model \
        --token_file /path/to/real_test_u.tok \
        --label_file /path/to/real_test_u.label \
        --disfluent_file /path/to/real_test.dis \
        --output_file /path/to/real_test_predict.flu
"""

import argparse
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


def merge_subwords_and_labels(tokens, labels):
    """Merge subword tokens (##) and align labels with final words."""
    words, word_labels = [], []
    current_word, current_label = "", None

    for tok, lab in zip(tokens, labels):
        if tok.startswith("##"):
            current_word += tok[2:]
        else:
            if current_word:
                words.append(current_word)
                word_labels.append(current_label)
            current_word = tok
            current_label = lab

    if current_word:
        words.append(current_word)
        word_labels.append(current_label)

    return words, word_labels


def main():
    # Parse arguments
    parser = argparse.ArgumentParser(
        description="Generate fluent sentences from tokenized inputs and predicted labels"
    )
    parser.add_argument(
        "--generator_model", type=str, required=True,
        help="Path to the language model for generation"
    )
    parser.add_argument(
        "--token_file", type=str, required=True,
        help="File containing tokenized input"
    )
    parser.add_argument(
        "--label_file", type=str, required=True,
        help="File containing predicted labels"
    )
    parser.add_argument(
        "--disfluent_file", type=str, required=True,
        help="File containing original disfluent sentences"
    )
    parser.add_argument(
        "--output_file", type=str, required=True,
        help="Output file to save generated fluent sentences"
    )
    args = parser.parse_args()

    # Clear CUDA cache
    torch.cuda.empty_cache()

    # Load model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.generator_model)
    model = AutoModelForCausalLM.from_pretrained(
        args.generator_model,
        torch_dtype=torch.float16,
        device_map="auto"
    )

    # Read input files
    with open(args.token_file, "r", encoding="utf-8") as f_tok, \
         open(args.label_file, "r", encoding="utf-8") as f_label, \
         open(args.disfluent_file, "r", encoding="utf-8") as f_dis:

        token_lines = f_tok.readlines()
        label_lines = f_label.readlines()
        disfluent_lines = f_dis.readlines()

    assert len(token_lines) == len(label_lines) == len(disfluent_lines), \
        "Mismatch in input file lengths!"

    # Shared instruction prompt
    base_prompt = (
        "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
        "This sentence may contain disfluencies, including but not limited to repetitions, fillers, discourse markers, false starts, and other forms of disfluent speech in Marathi.\n\n"
        "Your task is to remove these disfluencies while preserving the grammatical structure and original meaning of the sentence.\n\n"
        "You are also provided with:\n\n"
        " Word+label pairs of the disfluent sentence, where:\n"
        "    • '1' = the word is disfluent and should be removed\n"
        "    • '0' = the word is fluent and should be retained\n\n"
        "After removing words labeled as '1', reconstruct the fluent sentence.\n\n"
        "Ensure that the final output is a well-formed, fluent sentence that conveys the same intended meaning as the original input, but without any disfluencies.\n\n"
        "Word+Label Pairs: {word_label_pairs}\n"
        "Disfluent Sentence: {disfluent}\n"
        "Fluent Sentence:"
    )


    # base_prompt = (
    #     "You are given a disfluent sentence in Marathi.\n"
    #     "Remove repetitions, fillers, false starts, and other forms of disfluent speech while keeping the meaning intact.\n"
    #     "The words marked as disfluent are: {word_label_pairs}\n\n"
    #     "Disfluent Sentence:\n"
    #     "{disfluent}\n\n"
    #     "Fluent Sentence:"
    # )



    

    # Generate fluent outputs
    with open(args.output_file, "w", encoding="utf-8") as fout:
        for tokens, labels, disfluent in zip(token_lines, label_lines, disfluent_lines):
            tokens = tokens.strip().split()
            labels = labels.strip().split()
            disfluent = disfluent.strip()

            # Merge subwords into full words with labels
            words, word_labels = merge_subwords_and_labels(tokens, labels)

            # Build word+label pairs
            word_label_pairs = [(w, l) for w, l in zip(words, word_labels)]

            # Construct full prompt
            prompt = base_prompt.format(
                word_label_pairs=word_label_pairs,
                disfluent=disfluent
            )

            # Tokenize
            inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

            # Generate output
            with torch.no_grad():
                output = model.generate(
                    **inputs,
                    max_new_tokens=256,
                    temperature=0.0,
                    top_p=1.0,
                    do_sample=False,
                    pad_token_id=tokenizer.eos_token_id
                )

            # Decode result
            result = tokenizer.decode(output[0], skip_special_tokens=True)

            # Extract just the fluent sentence
            if "Fluent Sentence:" in result:
                fluent_line = result.split("Fluent Sentence:")[-1].strip().split("\n")[0]
            else:
                fluent_line = result.strip()

            fout.write(fluent_line + "\n")


if __name__ == "__main__":
    main()
