# #!/usr/bin/env python3
# """
# Generate fluent sentences from disfluent ASR outputs using a trained language model (vLLM backend).

# Usage:
    # python generate_fluent_from_preds_vllm.py \
    #     --generator_model /path/to/final_model \
    #     --token_file /path/to/real_test_u.tok \
    #     --label_file /path/to/real_test_u.label \
    #     --disfluent_file /path/to/real_test.dis \
    #     --output_file /path/to/real_test_predict.flu
# """

# import argparse
# from vllm import LLM, SamplingParams


# def merge_subwords_to_words(tokens, labels):
#     """
#     Merge subword tokens (with ##) into whole words.
#     Labels are merged: if any subtoken is '1', the whole word is '1'.
#     """
#     words, word_labels = [], []
#     current_word, current_labels = "", []

#     for tok, lab in zip(tokens, labels):
#         if tok.startswith("##"):
#             current_word += tok[2:]
#             current_labels.append(lab)
#         else:
#             if current_word:
#                 words.append(current_word)
#                 word_labels.append("1" if "1" in current_labels else "0")
#             current_word = tok
#             current_labels = [lab]

#     if current_word:
#         words.append(current_word)
#         word_labels.append("1" if "1" in current_labels else "0")

#     return words, word_labels


# def main():
#     parser = argparse.ArgumentParser(
#         description="Generate fluent sentences from token+label inputs (vLLM)"
#     )
#     parser.add_argument("--generator_model", type=str, required=True,
#                         help="Path to the trained model (for vLLM)")
#     parser.add_argument("--token_file", type=str, required=True,
#                         help="File containing subword tokens (space-separated)")
#     parser.add_argument("--label_file", type=str, required=True,
#                         help="File containing subword labels (space-separated)")
#     parser.add_argument("--disfluent_file", type=str, required=True,
#                         help="File containing original disfluent sentences")
#     parser.add_argument("--output_file", type=str, required=True,
#                         help="Output file for saving fluent sentences")
#     args = parser.parse_args()

#     # Load vLLM model
#     llm = LLM(model=args.generator_model, trust_remote_code=True,gpu_memory_utilization=0.2, max_model_len=4096)

#     # Sampling configuration (similar to your HF generate params)
#     sampling_params = SamplingParams(
#         temperature=0.0,
#         top_p=1.0,
#         max_tokens=256,
#         repetition_penalty=1.2,

#     )

#     # Read inputs
#     with open(args.token_file, "r", encoding="utf-8") as f_tok, \
#          open(args.label_file, "r", encoding="utf-8") as f_lab, \
#          open(args.disfluent_file, "r", encoding="utf-8") as f_dis:

#         token_lines = f_tok.readlines()
#         label_lines = f_lab.readlines()
#         disfluent_lines = f_dis.readlines()

#     assert len(token_lines) == len(label_lines) == len(disfluent_lines), \
#         "Mismatch in input file lengths!"

#     # Base prompt
    # base_prompt = (
    #     "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
    #     "This sentence may contain disfluencies, including but not limited to repetitions, fillers, discourse markers, false starts, and other forms of disfluent speech in Hindi, Bengali and Marathi.\n\n"
    #     "Your task is to remove these disfluencies while preserving the grammatical structure and original meaning of the sentence.\n\n"
    #     "You are also provided with:\n\n"
    #     "- A word-tokenized version of the disfluent sentence, and\n"
    #     "- A sequence of predicted labels for each word, where:\n"
    #     "    • '1' = the word is disfluent and should be removed\n"
    #     "    • '0' = the word is fluent and should be retained\n\n"
    #     "Here is an example of word-label pairs:\n"
    #     "    Hindi: [(\"यह\", 0), (\"किसानों\", 1), (\"के\", 1), (\"किसानों\", 0), (\"के\", 0), (\"पुरुषार्थ\", 0)]\n\n"
    #     "After removing words labeled as '1', reconstruct the fluent sentence.\n\n"
    #     "Ensure that the final output is a well-formed, fluent sentence that conveys the same intended meaning as the original input, but without any disfluencies."
    # )

#     prompts = []
#     for tokens, labels, disfluent in zip(token_lines, label_lines, disfluent_lines):
#         tokens = tokens.strip().split()
#         labels = labels.strip().split()
#         disfluent = disfluent.strip()

#         assert len(tokens) == len(labels), \
#             f"Mismatch in token/label length for: {disfluent}"

#         # Convert subword-level → word-level
#         words, word_labels = merge_subwords_to_words(tokens, labels)

#         # Build prompt
#         word_label_pairs = [(w, l) for w, l in zip(words, word_labels)]
#         prompt = (
#             f"{base_prompt}\n"
#             f"Word + Label pairs: {word_label_pairs}\n"
#             f"Disfluent Sentence: {disfluent}\n"
#             f"Fluent Sentence:"
#         )
#         prompts.append(prompt)

#     # Run inference in batch
#     outputs = llm.generate(prompts, sampling_params)

#     # Write results
#     with open(args.output_file, "w", encoding="utf-8") as fout:
#         for output in outputs:
#             result = output.outputs[0].text.strip()
#             if "Fluent Sentence:" in result:
#                 fluent_line = result.split("Fluent Sentence:")[-1].strip().split("\n")[0]
#             else:
#                 fluent_line = result.strip()
#             fout.write(fluent_line + "\n")


# if __name__ == "__main__":
#     main()



#!/usr/bin/env python3
import argparse
import torch
import ast
from vllm import LLM, SamplingParams


def merge_subwords_and_labels(tokens, labels):
    words, word_labels = [], []
    current_word, current_label = "", None

    for tok, lab in zip(tokens, labels):
        if tok.startswith("##"):
            current_word += tok[2:]
        else:
            if current_word:
                words.append(current_word)
                word_labels.append(current_label)
            current_word = tok
            current_label = lab

    if current_word:
        words.append(current_word)
        word_labels.append(current_label)

    return words, word_labels


def merge_subwords(tokens):
    words = []
    current_word = ""

    for tok in tokens:
        if tok.startswith("##"):
            current_word += tok[2:]
        else:
            if current_word:
                words.append(current_word)
            current_word = tok
    if current_word:
        words.append(current_word)

    return words


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--generator_model", type=str, required=True)
    parser.add_argument("--token_file", type=str, required=True)
    parser.add_argument("--label_file", type=str, required=True)
    parser.add_argument("--disfluent_file", type=str, required=True)
    parser.add_argument("--fluent_output", type=str, required=True)
    parser.add_argument("--labels_output", type=str, required=True)
    args = parser.parse_args()

    torch.cuda.empty_cache()

    # Load model with vLLM
    llm = LLM(
        model=args.generator_model,
        dtype="float16",
        trust_remote_code=True,
        gpu_memory_utilization=0.2,
        max_model_len=4096
    )

    sampling_params = SamplingParams(
        temperature=0.0,
        top_p=1.0,
        max_tokens=256,
        repetition_penalty=1.2,
    )

    with open(args.token_file, "r", encoding="utf-8") as f_tok, \
         open(args.label_file, "r", encoding="utf-8") as f_label, \
         open(args.disfluent_file, "r", encoding="utf-8") as f_dis:

        token_lines = f_tok.readlines()
        label_lines = f_label.readlines()
        disfluent_lines = f_dis.readlines()

    assert len(token_lines) == len(label_lines) == len(disfluent_lines), \
        "Mismatch in input file lengths!"

    base_prompt = (
        "You are given a disfluent sentence generated by an Automatic Speech Recognition (ASR) system.\n"
        "This sentence may contain disfluencies, including but not limited to repetitions, fillers, discourse markers, false starts, and other forms of disfluent speech in Hindi, Bengali and Marathi.\n\n"
        "Your task is to remove these disfluencies while preserving the grammatical structure and original meaning of the sentence.\n\n"
        "You are also provided with:\n\n"
        "- Word+label pairs of the disfluent sentence, where:\n"
        "    • '1' = the word is disfluent and should be removed\n"
        "    • '0' = the word is fluent and should be retained\n\n"
        "After removing words labeled as '1', reconstruct the fluent sentence.\n\n"
        "Ensure that the final output is a well-formed, fluent sentence that conveys the same intended meaning as the original input, but without any disfluencies.\n\n"
        "Word+Label Pairs: {word_label_pairs}\n"
        "Disfluent Sentence: {disfluent}\n"
        "Fluent Sentence:"
    )

    with open(args.fluent_output, "w", encoding="utf-8") as f_fluent, \
         open(args.labels_output, "w", encoding="utf-8") as f_labels:

        for tokens, labels, disfluent in zip(token_lines, label_lines, disfluent_lines):
            tokens = ast.literal_eval(tokens.strip())
            labels = ast.literal_eval(labels.strip())
            disfluent = disfluent.strip()

            # Merge tokens & labels
            words, word_labels = merge_subwords_and_labels(tokens, labels)
            merged_disfluent_tokens = merge_subwords(tokens)

            word_label_pairs = [(w, l) for w, l in zip(words, word_labels)]

            prompt = base_prompt.format(
                word_label_pairs=word_label_pairs,
                disfluent=disfluent,
                disfluent_tokens=" ".join(merged_disfluent_tokens)
            )

            outputs = llm.generate([prompt], sampling_params)
            result = outputs[0].outputs[0].text.strip()

            if "Fluent Sentence:" in result:
                fluent_line = result.split("Fluent Sentence:")[-1].strip().split("\n")[0]
            else:
                fluent_line = result.strip()

            # Write fluent sentence to file
            f_fluent.write(fluent_line + "\n")

            # Write merged tokens with labels to another file
            f_labels.write(str(list(zip(words, word_labels))) + "\n")


if __name__ == "__main__":
    main()
